# Base da Imagem
FROM ubuntu

# Adicionar o metadata para a imagem com o par: chave,valor
LABEL maintainer="Fernando Anselmo <fernando.anselmo74@gmail.com>"
LABEL version="1.4"

# Variaveis de Ambiente
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PATH=/opt/conda/bin:$PATH

# Execucoes iniciais:
    # 1. Criar a pasta de ligacao
RUN mkdir ~/GitProjects

    # 2. Adicionar a Zona Geografica correta
RUN ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime

    # 3. Instalar os pacotes necessarios
RUN apt update && \
    apt install --no-install-recommends --yes wget apt-utils ca-certificates pkg-config \
      git-all tzdata

    # 4. Proceder limpeza inicial
RUN apt autoclean -y && \
    apt autoremove -y
    
    # 5. Instalar o Anaconda
RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \ 
    wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm -f ~/anaconda.sh && \
    conda install nodejs && \
    conda update --all -y

    # 6. Proceder limpeza basica no Anaconda
RUN conda uninstall -y anaconda-navigator && \
    pip uninstall -y spyder && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.pyc' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    find /opt/conda/lib/python*/site-packages/bokeh/server/static -follow -type f -name '*.js' ! -name '*.min.js' -delete && \
    conda clean -atiy

    # 7. Instalar os pacotes
RUN pip install scipy SQLAlchemy missingno json_tricks \
        gensim elasticsearch psycopg2-binary pymc3 apyori

    # 8. Instalar o pacote: nbextensions
# RUN pip install jupyter_contrib_nbextensions jupyter_nbextensions_configurator

    # 9. Instalar os temas para o Jupyter
RUN pip install msgpack jupyterthemes && \
    jt -t grade3

    # 10. Habilitar as extensoes do Jupyter Notebook
# RUN jupyter contrib nbextension install --user && \
#    jupyter nbextensions_configurator enable --user && \
#    jupyter nbextension enable codefolding/main && \
#    jupyter nbextension enable collapsible_headings/main

    # 11. Adicionar a extensao do vim-binding
# RUN mkdir -p $(jupyter --data-dir)/nbextensions && \
#    git clone https://github.com/lambdalisue/jupyter-vim-binding $(jupyter --data-dir)/nbextensions/vim_binding && \
#    cd $(jupyter --data-dir)/nbextensions && \
#    chmod -R go-w vim_binding

    # 12. Adicionar o Git ao Jupyter Lab
RUN pip install --upgrade jupyterlab-git && \
    jupyter lab build

    # 13. Proceder limpeza final
RUN conda clean -atiy && \
    apt remove -y wget pkg-config && \
    apt autoremove -y && \
    apt autoclean -y

# Configurar o acesso ao Jupyter
WORKDIR /root/GitProjects
EXPOSE 8888
CMD jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='data-science'
